### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "t" is null

### ISSUE THREAD

**Issue by molostoff** [grosenberg/IndentGuide#25]
Updated Eclipse, reinstalled IndentGuide, but opening pligin Preferences Page caused error:

Unable to create the selected preference page.

Exception stack trace:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:77)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:204)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:281)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceNode.createPage(WorkbenchPreferenceNode.java:52)
	at org.eclipse.jface.preference.PreferenceDialog.createPage(PreferenceDialog.java:1281)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.createPage(FilteredPreferenceDialog.java:338)
	at org.eclipse.jface.preference.PreferenceDialog.showPage(PreferenceDialog.java:1167)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.showPage(FilteredPreferenceDialog.java:630)
	at org.eclipse.jface.preference.PreferenceDialog$5.lambda$0(PreferenceDialog.java:661)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.jface.preference.PreferenceDialog$5.selectionChanged(PreferenceDialog.java:658)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:821)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:818)
	at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1191)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:284)
	at org.eclipse.jface.util.OpenStrategy$1.lambda$1(OpenStrategy.java:438)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:66)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "t" is null
	at net.certiv.tools.indentguide.preferences.GuidePage.lambda$1(GuidePage.java:66)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.certiv.tools.indentguide.preferences.GuidePage.<init>(GuidePage.java:67)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	... 58 more

Session Data:
 eclipse.buildId=4.27.0.20230309-1200
java.version=19.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=ru_RU
Framework arguments:  -product org.eclipse.epp.package.php.product
Command-line arguments:  -data file:~/eclipse-workspace/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.php.product

Plugin Version:
  IndentGuide	2.0.0.20230220-0508	net.certiv.tools.indentguide.feature.feature.group	Certiv Analytis

**Comment by molostoff** [comment]
reinstalled from https://github.com/grosenberg/IndentGuide/releases/tag/v2.2.0
caused the same error:

java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "t" is null
	at net.certiv.tools.indentguide.preferences.GuidePage.lambda$1(GuidePage.java:68)

**Comment by grosenberg** [comment]
Cannot reproduce, though this is the second report of the problem.

What is the contents of `net.certiv.tools.indentguide.prefs` in `<eclipse-workspace>/.metadata/.plugins/org.eclipse.core.runtime/.settings/` ? Do the permissions look correct?

<s>Try removing that file and see if the problem goes away.</s> Try the new pre-release

[net.certiv.tools.indentguide.site-2.2.0-SNAPSHOT.zip](https://github.com/grosenberg/IndentGuide/files/11054788/net.certiv.tools.indentguide.site-2.2.0-SNAPSHOT.zip)

**Comment by molostoff** [comment]
perms looks writable

contents before removal are:

eclipse.preferences.version=1
indentguide.content_types=org.eclipse.core.runtime.text|org.eclipse.cdt.autotools.ui.autoconf|org.eclipse.wst.jsdt.core.jsSource|org.eclipse.egit.patch|org.jkiss.dbeaver.sql|org.eclipse.mylyn.wikitext|org.eclipse.mylyn.wikitext.confluence|org.eclipse.mylyn.wikitext.asciidoc|org.eclipse.mylyn.wikitext.markdown|org.eclipse.mylyn.wikitext.twiki|org.eclipse.mylyn.wikitext.textile|org.eclipse.mylyn.wikitext.mediawiki|org.eclipse.mylyn.wikitext.tracwiki|org.eclipse.wst.dtd.core.dtdsource|org.eclipse.wildwebdeveloper.parent|org.eclipse.wildwebdeveloper.json|org.eclipse.php.composer.core.composerJson|org.eclipse.wildwebdeveloper.json.lerna|org.eclipse.wildwebdeveloper.json.npmpackage|org.eclipse.wildwebdeveloper.json.eslintrc|org.eclipse.wildwebdeveloper.json.typings|org.eclipse.wildwebdeveloper.json.jsconfig|org.eclipse.wildwebdeveloper.json.omnisharp|org.eclipse.wildwebdeveloper.json.bower|org.eclipse.wildwebdeveloper.json.tsconfig|org.eclipse.wildwebdeveloper.json.bowerrc|org.eclipse.wildwebdeveloper.json.tslint|org.eclipse.wildwebdeveloper.scss|org.eclipse.wildwebdeveloper.yaml|org.eclipse.wildwebdeveloper.ts|org.eclipse.wildwebdeveloper.jsx|org.eclipse.wildwebdeveloper.css|org.eclipse.wildwebdeveloper.html|org.eclipse.wildwebdeveloper.js|org.eclipse.wildwebdeveloper.tsx|org.eclipse.wildwebdeveloper.less|org.eclipse.cdt.managedbuilder.llvm.ui.llvmAssemblyCode|org.eclipse.php.core.phpsource|org.eclipse.wst.xml.core.xmlsource|org.eclipse.cdt.managedbuilder.llvm.ui.llvmAssemblySource|org.eclipse.team.genericeditor.diff.extension.patch|org.eclipse.emf.codegen.jet|com.boothen.jsonedit.core.jsonsource|org.eclipse.jdt.core.javaSource|org.eclipse.wb.core.java.javaSourceGUI|org.eclipse.cdt.autotools.ui.automake|org.eclipse.linuxtools.stap.content-type|org.eclipse.jst.jsp.core.jspsource|org.eclipse.jst.jsp.core.cssjspsource|org.eclipse.jst.jsp.core.cssjspfragmentsource|org.eclipse.jst.jsp.core.tagsource|org.eclipse.jst.jsp.core.tagxsource|org.eclipse.jst.jsp.core.jspfragmentsource|org.eclipse.jdt.core.JARManifest|org.eclipse.pde.bundleManifest|org.eclipse.cdt.core.asmSource|org.eclipse.wst.html.core.htmlsource|jsf.facelet|jsf.facelet.composite|com.dubture.twig.core.twigtemplate|org.dadacoalition.yedit.yamlsource|org.eclipse.wst.json.core.jsonsource|org.eclipse.wst.json.jshint.core.jshintrcsource|org.eclipse.wst.json.bower.core.bowersource|org.eclipse.wst.json.npm.core.npmsource|org.eclipse.wst.json.eslint.core.eslintsource|org.eclipse.wst.json.bower.core.bowerrcsource|org.eclipse.ltk.core.refactoring.refactoringIndex|org.eclipse.ui.views.log.log|org.eclipse.wst.css.core.csssource|org.eclipse.ui.texteditor|org.eclipse.cdt.core.cSource|org.eclipse.cdt.core.cHeader|org.eclipse.cdt.core.cxxSource|org.eclipse.cdt.core.cxxHeader|org.eclipse.cdt.make.core.makefile|org.jkiss.dbeaver.json|org.eclipse.wst.jsdt.core.jsonSource|org.eclipse.jdt.core.javaProperties|org.eclipse.pde.buildProperties|org.eclipse.pde.pluginProperties|org.eclipse.core.resources.preferences|org.eclipse.linuxtools.docker.editor.ls|org.eclipse.egit.contenttype.gitignore|org.eclipse.core.runtime.xml|org.eclipse.jst.ws.axis.consumption.core.wsddsource|org.eclipse.pde.fragmentManifest|org.eclipse.jst.j2ee.webDD|org.eclipse.jst.jee.ee7ejbDD|org.eclipse.jst.jsp.core.tldsource|org.eclipse.jst.jee.ee6webfragmentDD|org.eclipse.pde.schema|org.eclipse.jst.jee.web.xml.contenttype.webXMLConfigFile|org.eclipse.wst.ws.wsilsource|org.eclipse.jst.j2ee.ejbDD|org.eclipse.jst.jee.ee5ejbDD|org.eclipse.pde.targetFile|org.eclipse.pde.siteManifest|net.sourceforge.dep4e.plugin.editors.contentTypes|org.eclipse.e4.content-type|org.eclipse.jst.jee.ee7webDD|org.eclipse.wildwebdeveloper.xsl|org.eclipse.jst.jee.ee7appclientDD|org.eclipse.jst.jee.ee6earDD|org.eclipse.wildwebdeveloper.xsd|org.eclipse.jst.jee.ee8appclientDD|org.apache.struts2.ide.contenttype.struts2ConfigFile|org.eclipse.jst.j2ee.earDD|org.eclipse.pde.simpleCheatSheet|org.eclipse.pde.ctxHelpFile|org.apache.struts2.ide.contenttype.xworkValidatorConfig|org.eclipse.jst.jee.ee7webfragmentDD|org.eclipse.ant.core.antBuildFile|org.eclipse.pde.productFile|org.eclipse.jst.jee.ee5webDD|org.eclipse.jst.jsf.facesconfig.facesConfigFile|org.eclipse.jst.jee.ee6connectorDD|org.eclipse.wst.xml.core.xslsource|org.eclipse.jst.j2ee.connectorDD|org.eclipse.jst.jee.ee6webDD|org.eclipse.pde.ds.core.content-type|org.eclipse.pde.ds.annotations.content-type-v13|org.eclipse.pde.ds.annotations.content-type-v12|org.eclipse.jst.jee.ee8connectorDD|org.eclipse.jst.jee.ee6ejbDD|org.apache.struts2.ide.contenttype.xworkValidator|org.eclipse.pde.tocFile|org.eclipse.jst.jee.ee5appclientDD|org.eclipse.jst.jee.ee8webDD|org.eclipse.jst.jee.ee5earDD|org.eclipse.m2e.core.pomFile|org.eclipse.jst.jee.ee6appclientDD|org.eclipse.vex.ui.XmlDocument|org.eclipse.vex.ui.xhtml|org.eclipse.vex.ui.dita|org.eclipse.wst.xsl.core.content-type.docbooksource|org.eclipse.wst.wsdl.wsdlsource|org.eclipse.bpel.contenttype|org.eclipse.wst.xsd.core.xsdsource|org.eclipse.pde.featureManifest|org.eclipse.bpmn2.content-type.xml|org.eclipse.wildwebdeveloper.dtd|org.eclipse.jst.jee.ee8ejbDD|org.eclipse.pde.pluginManifest|org.eclipse.xsd|org.eclipse.jst.jee.ee8webfragmentDD|org.eclipse.jst.jee.ee8earDD|org.eclipse.jst.jee.ee7connectorDD|org.eclipse.jst.server.jetty.xml.contenttype.jettyConfigFile|org.eclipse.pde.compositeCheatSheet|org.eclipse.emf.ecore.xmi|org.eclipse.emf.ecore|org.eclipse.emf.emof|org.eclipse.oomph.setup|org.eclipse.bpmn2.content-type.xmi|org.eclipse.pde.categoryManifest|org.eclipse.wst.xml.core.xmisource|org.eclipse.jdt.junit.JUnitResult|org.eclipse.jst.jee.ee7earDD|org.eclipse.jst.j2ee.appclientDD|org.eclipse.wst.xsl.core.content-type.ditasource|org.eclipse.bpel.apache.ode.deploy.ui.content-type|org.python.pydev.pythonfile|org.eclipse.ltk.core.refactoring.refactoringHistory|org.jkiss.dbeaver.erd.content-type-erd
indentguide.draw_blank_line=false
indentguide.draw_left_end=false
indentguide.enabled=true
indentguide.line_alpha=68
indentguide.line_color=52,101,164
indentguide.line_shift=3
indentguide.line_style=2
indentguide.skip_comment_block=true

**Comment by molostoff** [comment]
after removing prefs, I have restarted eclipse, prefs regenerated by setup tools with

eclipse.preferences.version=1
indentguide.content_types=org.eclipse.core.runtime.text|org.eclipse.cdt.autotools.ui.autoconf|org.eclipse.wst.jsdt.core.jsSource|org.eclipse.egit.patch|org.jkiss.dbeaver.sql|org.eclipse.mylyn.wikitext|org.eclipse.mylyn.wikitext.confluence|org.eclipse.mylyn.wikitext.asciidoc|org.eclipse.mylyn.wikitext.markdown|org.eclipse.mylyn.wikitext.twiki|org.eclipse.mylyn.wikitext.textile|org.eclipse.mylyn.wikitext.mediawiki|org.eclipse.mylyn.wikitext.tracwiki|org.eclipse.wst.dtd.core.dtdsource|org.eclipse.wildwebdeveloper.parent|org.eclipse.wildwebdeveloper.json|org.eclipse.php.composer.core.composerJson|org.eclipse.wildwebdeveloper.json.lerna|org.eclipse.wildwebdeveloper.json.npmpackage|org.eclipse.wildwebdeveloper.json.eslintrc|org.eclipse.wildwebdeveloper.json.typings|org.eclipse.wildwebdeveloper.json.jsconfig|org.eclipse.wildwebdeveloper.json.omnisharp|org.eclipse.wildwebdeveloper.json.bower|org.eclipse.wildwebdeveloper.json.tsconfig|org.eclipse.wildwebdeveloper.json.bowerrc|org.eclipse.wildwebdeveloper.json.tslint|org.eclipse.wildwebdeveloper.scss|org.eclipse.wildwebdeveloper.yaml|org.eclipse.wildwebdeveloper.ts|org.eclipse.wildwebdeveloper.jsx|org.eclipse.wildwebdeveloper.css|org.eclipse.wildwebdeveloper.html|org.eclipse.wildwebdeveloper.js|org.eclipse.wildwebdeveloper.tsx|org.eclipse.wildwebdeveloper.less|org.eclipse.cdt.managedbuilder.llvm.ui.llvmAssemblyCode|org.eclipse.php.core.phpsource|org.eclipse.wst.xml.core.xmlsource|org.eclipse.cdt.managedbuilder.llvm.ui.llvmAssemblySource|org.eclipse.team.genericeditor.diff.extension.patch|org.eclipse.emf.codegen.jet|com.boothen.jsonedit.core.jsonsource|org.eclipse.jdt.core.javaSource|org.eclipse.wb.core.java.javaSourceGUI|org.eclipse.cdt.autotools.ui.automake|org.eclipse.linuxtools.stap.content-type|org.eclipse.jst.jsp.core.jspsource|org.eclipse.jst.jsp.core.cssjspsource|org.eclipse.jst.jsp.core.cssjspfragmentsource|org.eclipse.jst.jsp.core.tagsource|org.eclipse.jst.jsp.core.tagxsource|org.eclipse.jst.jsp.core.jspfragmentsource|org.eclipse.jdt.core.JARManifest|org.eclipse.pde.bundleManifest|org.eclipse.cdt.core.asmSource|org.eclipse.wst.html.core.htmlsource|jsf.facelet|jsf.facelet.composite|com.dubture.twig.core.twigtemplate|org.dadacoalition.yedit.yamlsource|org.eclipse.wst.json.core.jsonsource|org.eclipse.wst.json.jshint.core.jshintrcsource|org.eclipse.wst.json.bower.core.bowersource|org.eclipse.wst.json.npm.core.npmsource|org.eclipse.wst.json.eslint.core.eslintsource|org.eclipse.wst.json.bower.core.bowerrcsource|org.eclipse.ltk.core.refactoring.refactoringIndex|org.eclipse.ui.views.log.log|org.eclipse.wst.css.core.csssource|org.eclipse.ui.texteditor|org.eclipse.cdt.core.cSource|org.eclipse.cdt.core.cHeader|org.eclipse.cdt.core.cxxSource|org.eclipse.cdt.core.cxxHeader|org.eclipse.cdt.make.core.makefile|org.jkiss.dbeaver.json|org.eclipse.wst.jsdt.core.jsonSource|org.eclipse.jdt.core.javaProperties|org.eclipse.pde.buildProperties|org.eclipse.pde.pluginProperties|org.eclipse.core.resources.preferences|org.eclipse.linuxtools.docker.editor.ls|org.eclipse.egit.contenttype.gitignore|org.eclipse.core.runtime.xml|org.eclipse.jst.ws.axis.consumption.core.wsddsource|org.eclipse.pde.fragmentManifest|org.eclipse.jst.j2ee.webDD|org.eclipse.jst.jee.ee7ejbDD|org.eclipse.jst.jsp.core.tldsource|org.eclipse.jst.jee.ee6webfragmentDD|org.eclipse.pde.schema|org.eclipse.jst.jee.web.xml.contenttype.webXMLConfigFile|org.eclipse.wst.ws.wsilsource|org.eclipse.jst.j2ee.ejbDD|org.eclipse.jst.jee.ee5ejbDD|org.eclipse.pde.targetFile|org.eclipse.pde.siteManifest|net.sourceforge.dep4e.plugin.editors.contentTypes|org.eclipse.e4.content-type|org.eclipse.jst.jee.ee7webDD|org.eclipse.wildwebdeveloper.xsl|org.eclipse.jst.jee.ee7appclientDD|org.eclipse.jst.jee.ee6earDD|org.eclipse.wildwebdeveloper.xsd|org.eclipse.jst.jee.ee8appclientDD|org.apache.struts2.ide.contenttype.struts2ConfigFile|org.eclipse.jst.j2ee.earDD|org.eclipse.pde.simpleCheatSheet|org.eclipse.pde.ctxHelpFile|org.apache.struts2.ide.contenttype.xworkValidatorConfig|org.eclipse.jst.jee.ee7webfragmentDD|org.eclipse.ant.core.antBuildFile|org.eclipse.pde.productFile|org.eclipse.jst.jee.ee5webDD|org.eclipse.jst.jsf.facesconfig.facesConfigFile|org.eclipse.jst.jee.ee6connectorDD|org.eclipse.wst.xml.core.xslsource|org.eclipse.jst.j2ee.connectorDD|org.eclipse.jst.jee.ee6webDD|org.eclipse.pde.ds.core.content-type|org.eclipse.pde.ds.annotations.content-type-v13|org.eclipse.pde.ds.annotations.content-type-v12|org.eclipse.jst.jee.ee8connectorDD|org.eclipse.jst.jee.ee6ejbDD|org.apache.struts2.ide.contenttype.xworkValidator|org.eclipse.pde.tocFile|org.eclipse.jst.jee.ee5appclientDD|org.eclipse.jst.jee.ee8webDD|org.eclipse.jst.jee.ee5earDD|org.eclipse.m2e.core.pomFile|org.eclipse.jst.jee.ee6appclientDD|org.eclipse.vex.ui.XmlDocument|org.eclipse.vex.ui.xhtml|org.eclipse.vex.ui.dita|org.eclipse.wst.xsl.core.content-type.docbooksource|org.eclipse.wst.wsdl.wsdlsource|org.eclipse.bpel.contenttype|org.eclipse.wst.xsd.core.xsdsource|org.eclipse.pde.featureManifest|org.eclipse.bpmn2.content-type.xml|org.eclipse.wildwebdeveloper.dtd|org.eclipse.jst.jee.ee8ejbDD|org.eclipse.pde.pluginManifest|org.eclipse.xsd|org.eclipse.jst.jee.ee8webfragmentDD|org.eclipse.jst.jee.ee8earDD|org.eclipse.jst.jee.ee7connectorDD|org.eclipse.jst.server.jetty.xml.contenttype.jettyConfigFile|org.eclipse.pde.compositeCheatSheet|org.eclipse.emf.ecore.xmi|org.eclipse.emf.ecore|org.eclipse.emf.emof|org.eclipse.oomph.setup|org.eclipse.bpmn2.content-type.xmi|org.eclipse.pde.categoryManifest|org.eclipse.wst.xml.core.xmisource|org.eclipse.jdt.junit.JUnitResult|org.eclipse.jst.jee.ee7earDD|org.eclipse.jst.j2ee.appclientDD|org.eclipse.wst.xsl.core.content-type.ditasource|org.eclipse.bpel.apache.ode.deploy.ui.content-type|org.python.pydev.pythonfile|org.eclipse.ltk.core.refactoring.refactoringHistory|org.jkiss.dbeaver.erd.content-type-erd
indentguide.draw_blank_line=false
indentguide.draw_left_end=false
indentguide.line_shift=3
indentguide.line_style=2
indentguide.skip_comment_block=true


error still the same

**Comment by grosenberg** [comment]
You were too fast!  Uploaded a new pre-release -- see edit to prior reponse.

**Comment by grosenberg** [comment]
One more try.

If this does not work, provide the actual prefs file.

[net.certiv.tools.indentguide.site-2.2.0-SNAPSHOT.zip](https://github.com/grosenberg/IndentGuide/files/11054897/net.certiv.tools.indentguide.site-2.2.0-SNAPSHOT.zip)

**Comment by molostoff** [comment]
Works fine! Thank you very much!
My apologies for inconvenience, I have so much love this extension

**Comment by grosenberg** [comment]
Great!
